repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: pretty-format-json
      - id: name-tests-test
        exclude: "(^.vscode/|dicom_converter/_version.py)"

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
#repos:
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.3.0
#    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
#    -   id: check-yaml
#    -   id: debug-statements
#    -   id: double-quote-string-fixer
#    -   id: name-tests-test
#    -   id: requirements-txt-fixer
#-   repo: https://github.com/asottile/setup-cfg-fmt
#    rev: v1.20.1
#    hooks:
#    -   id: setup-cfg-fmt
#-   repo: https://github.com/asottile/reorder_python_imports
#    rev: v3.1.0
#    hooks:
#    -   id: reorder-python-imports
#        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
#        args: [--py37-plus, --add-import, 'from __future__ import annotations']
#-   repo: https://github.com/asottile/add-trailing-comma
#    rev: v2.2.3
#    hooks:
#    -   id: add-trailing-comma
#        args: [--py36-plus]
#-   repo: https://github.com/asottile/pyupgrade
#    rev: v2.34.0
#    hooks:
#    -   id: pyupgrade
#        args: [--py37-plus]
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.6.0
#    hooks:
#    -   id: autopep8
#-   repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#    -   id: flake8
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.961
#    hooks:
#    -   id: mypy
#        additional_dependencies: [types-all]
#        exclude: ^testing/resources/
